-- AlterTable
ALTER TABLE "Building" ALTER COLUMN "street" DROP NOT NULL,
ALTER COLUMN "houseNumber" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Unit" ALTER COLUMN "number" DROP NOT NULL,
ALTER COLUMN "type" DROP NOT NULL,
ALTER COLUMN "size" DROP NOT NULL,
ALTER COLUMN "coOwnershipShare" DROP NOT NULL;
